CREATE TABLE "street" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(100) NOT NULL
);

CREATE TABLE "material" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(100) NOT NULL,
  "price" INTEGER DEFAULT 0,
  "unit" VARCHAR(10) NOT NULL
);

CREATE TABLE "service" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(100) NOT NULL,
  "additional" BOOLEAN DEFAULT TRUE,
  "consume_materials" BOOLEAN DEFAULT FALSE,
  "change_tariff" BOOLEAN DEFAULT FALSE,
  "connection_service" BOOLEAN DEFAULT FALSE,
  "disconnection_service" BOOLEAN DEFAULT FALSE
);

CREATE TABLE "service_price" (
  "service_id" INTEGER,
  "date" DATE,
  "price" INTEGER DEFAULT 0,
  PRIMARY KEY("service_id", "date"),
  FOREIGN KEY ("service_id") REFERENCES "service"("id")
);

CREATE TABLE "tariff" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(100) NOT NULL,
  "digital" BOOLEAN NOT NULL,
  "channels" VARCHAR(4) DEFAULT '' NOT NULL
);

CREATE TABLE "tariff_price" (
  "tariff_id" INTEGER,
  "date" DATE,
  "price" INTEGER DEFAULT 0,
  PRIMARY KEY("tariff_id", "date"),
  FOREIGN KEY ("tariff_id") REFERENCES "tariff"("id")
);

CREATE TABLE "subscriber" (
  "id" INTEGER IDENTITY PRIMARY KEY,
  "account" INTEGER NOT NULL,
  "name" VARCHAR(64) NOT NULL,
  "balance" INTEGER DEFAULT 0 NOT NULL,
  "connected" BOOLEAN DEFAULT FALSE,
  "street_id" INTEGER,
  FOREIGN KEY ("street_id") REFERENCES "street"("id")
);

CREATE TABLE "subscriber_session" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subscriber_id" INTEGER NOT NULL,
  "connection_date" DATE NOT NULL,
  "disconnection_date" DATE DEFAULT NULL,
  FOREIGN KEY ("subscriber_id") REFERENCES "subscriber"("id")
);

CREATE TABLE "subscriber_tariff" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subscriber_id" INTEGER NOT NULL,
  "tariff_id" INTEGER NOT NULL,
  "connection_date" DATE NOT NULL,
  "disconnection_date" DATE DEFAULT NULL,
  FOREIGN KEY ("subscriber_id") REFERENCES "subscriber"("id"),
  FOREIGN KEY ("tariff_id") REFERENCES "tariff"("id")
);

CREATE TABLE "rendered_service" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subscriber_id" INTEGER NOT NULL,
  "service_id" INTEGER NOT NULL,
  "date" DATE NOT NULL,
  "price" INTEGER DEFAULT 0,
  FOREIGN KEY ("subscriber_id") REFERENCES "subscriber"("id"),
  FOREIGN KEY ("service_id") REFERENCES "service"("id")
);

CREATE TABLE "payment_type" (
  "id" INTEGER IDENTITY PRIMARY KEY,
  "name" VARCHAR(64) NOT NULL
);

CREATE TABLE "payment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subscriber_id" INTEGER NOT NULL,
  "service_id" INTEGER NOT NULL,
  "payment_type_id"  INTEGER,
  "date" DATE,
  "price" INTEGER DEFAULT 0,
  FOREIGN KEY ("subscriber_id") REFERENCES "subscriber"("id"),
  FOREIGN KEY ("service_id") REFERENCES "service"("id"),
  FOREIGN KEY ("payment_type_id") REFERENCES "payment_type"("id")
);

CREATE TABLE "material_consumption" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "material_id" INTEGER NOT NULL,
  "rendered_service_id" INTEGER NOT NULL,
  "amount" DOUBLE DEFAULT 0 NOT NULL,
  FOREIGN KEY ("material_id") REFERENCES "material"("id"),
  FOREIGN KEY ("rendered_service_id") REFERENCES "rendered_service"("id")
);
