CREATE TABLE IF NOT EXISTS `USER` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT
  , `USERNAME` VARCHAR(50) NOT NULL
  , `EMAIL` VARCHAR(50)
  , `PASSWORD` VARCHAR(60)
  , `CREATION_TIME` TIMESTAMP NOT NULL
  , `SOCIAL_MEDIA_SERVICE` VARCHAR(50)
  , `SOCIAL_ID` VARCHAR(100)
  , PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `IDEA` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT
  , `TITLE` VARCHAR(150) NOT NULL
  , `DESCRIPTION` VARCHAR(300) NOT NULL
  , `CREATION_TIME` TIMESTAMP NOT NULL
  , `MODIFICATION_TIME` TIMESTAMP NOT NULL
  , `RATING` INT NOT NULL
  , `USER_ID` BIGINT NOT NULL
  , `LATITUDE` DECIMAL(9,6) NULL
  , `LONGITUDE` DECIMAL(9,6) NULL
  , `IMAGE_URL` VARCHAR(512) NULL
  , PRIMARY KEY (`ID`)
  , CONSTRAINT `IDEAS_fk1` FOREIGN KEY (`USER_ID`) REFERENCES USER(`ID`)
);

CREATE TABLE IF NOT EXISTS `ROLE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT
  , `NAME` VARCHAR(10) NOT NULL
  , PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `USER_ROLE` (
  `USER_ID` BIGINT NOT NULL
  , `ROLE_ID` BIGINT NOT NULL
  , PRIMARY KEY (`USER_ID`,`ROLE_ID`)
  , CONSTRAINT `USER_ROLES_fk1` FOREIGN KEY (`USER_ID`) REFERENCES USER(`ID`)
  , CONSTRAINT `USER_ROLES_fk2` FOREIGN KEY (`ROLE_ID`) REFERENCES ROLE(`ID`)
);

CREATE TABLE IF NOT EXISTS `TAG` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT
  , `NAME` VARCHAR(20) NOT NULL
  , PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `IDEA_TAG` (
  `IDEA_ID` BIGINT NOT NULL
  , `TAG_ID` BIGINT NOT NULL
  , PRIMARY KEY (`IDEA_ID`,`TAG_ID`)
  , CONSTRAINT `IDEA_TAGS_fk1` FOREIGN KEY (`IDEA_ID`) REFERENCES IDEA(`ID`)
  , CONSTRAINT `IDEA_TAGS_fk2` FOREIGN KEY (`TAG_ID`) REFERENCES TAG(`ID`)
);

CREATE TABLE IF NOT EXISTS `COMMENT` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT
  , `USER_ID` BIGINT NOT NULL
  , `IDEA_ID` BIGINT NOT NULL
  , `BODY` VARCHAR(300) NOT NULL
  , `CREATION_TIME` TIMESTAMP NOT NULL
  , `MODIFICATION_TIME` TIMESTAMP NOT NULL
  , `RATING` INT NOT NULL
  , PRIMARY KEY (`ID`)
  , CONSTRAINT `COMMENTS_fk1` FOREIGN KEY (`USER_ID`) REFERENCES USER(`ID`)
  , CONSTRAINT `COMMENTS_fk2` FOREIGN KEY (`IDEA_ID`) REFERENCES IDEA(`ID`)
);

CREATE TABLE IF NOT EXISTS `UserConnection` (
    userId varchar(255) not null,
    providerId varchar(255) not null,
    providerUserId varchar(255),
    rank int not null,
    displayName varchar(255),
    profileUrl varchar(512),
    imageUrl varchar(512),
    accessToken varchar(255) not null,
    secret varchar(255),
    refreshToken varchar(255),
    expireTime bigint,
    primary key (userId, providerId, providerUserId),
    unique index UserConnectionRank(userId, providerId, rank));

